Arch unit
HuKuTa94/delivery pull request #14
Opened 2024-08-04 11:51 UTC by HuKuTa94

Добавлены архитектурные тесты.

2024-08-04 21:05 UTC, bas-kirill requested changes

2024-08-04 21:05 UTC, bas-kirill commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/ApiPackageTest.kt
> +        }
Гоу назовем `dependsOs`, более правильно по инглишу, но минорно, можешь закрыть, если считаешь такой вариант тоже ок 🙂

2024-08-04 21:05 UTC, bas-kirill commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/GeneralArchitectureTest.kt
> +
`CleanArchitectureTest`?🙂

2024-08-04 21:05 UTC, bas-kirill commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/ApplicationPackageTest.kt
> +                .check(packageClasses)
Если мы уже реализовали интерфейс, то дополнительно добавлять суфикс "Query" будет избыточно: мы можем просто посмотреть все реализации интерфейса и найти нужный поиском + это не будет в ущерб интроспекции. Давай уберем избыточный суффикс? 🙂

2024-08-04 21:05 UTC, bas-kirill commented on core/application/main/src/main/kotlin/github/com/hukuta94/delivery/core/application/query/courier/GetBusyCouriersQuery.kt
>  }
Можно сделать функциональный интерфейсом:
```
fun interface ...
```

2024-08-04 21:05 UTC, bas-kirill commented on core/application/main/src/main/kotlin/github/com/hukuta94/delivery/core/application/usecase/courier/MoveCouriersUseCase.kt
>  }
Честно хз дважды прописывать суффикс и потом еще реализовывать интерфейс: кмк изыбточность

зато так:
```
fun interface MoveCouriers : UseCase {
    fun execute()
}
```

я сразу акцентирую внимание что предоставляет интерфейс

2024-08-04 21:05 UTC, bas-kirill commented on architectureTests/src/main/kotlin/github/com/hukuta94/delivery/Packages.kt
> +
Тут все оч хорошо по неймингам, кмк излишние коменты

2024-08-04 21:05 UTC, bas-kirill commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/GeneralArchitectureTest.kt
> +
+ я бы еще накидал диаграмку с зависимостями, чтобы по `pom.xml` не лазить

2024-08-04 21:05 UTC, bas-kirill commented on architectureTests/src/main/kotlin/github/com/hukuta94/delivery/Rules.kt
> +}
Я бы совместил логику `notDependsOn` и `dependsOn`: если есть модули X, Y, Z и модуль X зависит от Y => он не зависит от Z. Тогда в коде запишем вместо:
```
X dependsOn Y
X notDependsOn Z
```

так:
```
X dependsOn Y
```
Что будет подразумевать что X зависит только Y, а если появилась связь с Z, то фейлим тест🙂

2024-08-04 21:05 UTC, bas-kirill commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/ApplicationPackageTest.kt
> +                .check(packageClasses)
кмк это уже не совсем про архитектуру, я бы не заставлял разработчиков обязательно добавлять суффикс `Impl`: совсем Плазменный Коммунизм 2.0, тем не менее на твое усмотрение 🙂

2024-08-04 21:05 UTC, bas-kirill commented on core/application/main/src/main/kotlin/github/com/hukuta94/delivery/core/application/query/common/LocationResponse.kt
>  package github.com.hukuta94.delivery.core.application.query.common
я бы из common в dto переместил, но на твое усмотрение 🙂

2024-08-04 21:05 UTC, bas-kirill commented on core/application/main/src/main/kotlin/github/com/hukuta94/delivery/core/application/usecase/UseCase.kt
> + */
кмк очев что это маркерный интерфейс, я бы не коментил 🙂

2024-08-04 21:05 UTC, bas-kirill commented on core/domain/main/src/main/kotlin/github/com/hukuta94/delivery/core/domain/ValueObject.kt
> +interface ValueObject
Я бы убрал коммент + через типы заставил бы реализовывать equals / hashCode, чтобы не багать:
```Kotlin
interface ValueObject<T> where T : ValueObject<T>, T : Cloneable
```

потом больно находить баги, если забыл проставить `data` перед `class` 🙂

2024-08-04 21:05 UTC, bas-kirill commented on api/adapter/http/src/main/kotlin/github/com/hukuta94/delivery/api/adapter/http/courier/CourierControllerV1.kt
>  import java.util.*
Грубо говоря, антибаза

2024-08-05 07:29 UTC, HuKuTa94 commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/ApiPackageTest.kt
> +        }
Да согласен, так будет правильнее. Еще была идея для этих проверок передавать список, чтобы можно было задать проверку так:

```kotlin
API_PACKAGE dependsOn setOf(
     APPLICATION_QUERY_PACKAGE,
     APPLICATION_USECASE_PACKAGE,
     APPLICATION_EVENT_PACKAGE
 )
```

2024-08-05 07:31 UTC, HuKuTa94 commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/GeneralArchitectureTest.kt
> +
Тут я хотел отобразить общие зависимости целых слоев. Как бы вид сверху, общий план)) Возможно, CleanArchitectureTest подходит лучше)

> я бы еще накидал диаграмку с зависимостями, чтобы по pom.xml не лазить

Раскрой, пожалуйста, мысль. Какая диаграмма имеется в виду и где её отобразить?

2024-08-05 07:35 UTC, HuKuTa94 commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/ApplicationPackageTest.kt
> +                .check(packageClasses)
Идея этого пакета (core.application.query) заключается в предоставлении интерфейсов запросов, которые могут иметь свою модель возвращаемых данных (Response). Эти интерфейсы реализуют только инфраструктурные адаптеры. 

Мне пока не удалось найти более выразительный способ без использования суфиксов или маркерных интерфейсов, чтобы контролировать архитектуру и располагаемые классы/интерфейсы внутри определенных пакетов. 

Здесь хочется задать контроль, что в пакете

- usecase должны быть только интерфейсы юзкейсов, а в usecase.impl только реализации этих интерфейсов и ничего больше.
- query должны быть только интерфейсы без реализаций + допускается наличие классов ДТО

и так далее

2024-08-05 07:36 UTC, HuKuTa94 commented on core/application/main/src/main/kotlin/github/com/hukuta94/delivery/core/application/query/courier/GetBusyCouriersQuery.kt
>  }
Расскажи подробнее, что имеется в виду.

2024-08-05 07:39 UTC, HuKuTa94 commented on core/application/main/src/main/kotlin/github/com/hukuta94/delivery/core/application/usecase/courier/MoveCouriersUseCase.kt
>  }
Соглашусь насчет избыточности, но как по мне оба варианта ок. С суффиксами хоть и избыточно, зато из кода будет однозначно понятно, что дело имеем именно с use case. Это может быть полезно для пока неопытной команды, которая переходит на ЧА.

2024-08-05 07:40 UTC, HuKuTa94 commented on architectureTests/src/main/kotlin/github/com/hukuta94/delivery/Packages.kt
> +
Опять же для неопытной команды, для которой ЧА в новинку, наличие таких блоков и комментариев поможет первое время ориентироваться и видеть общую архитектуру приложения :-)

2024-08-05 07:42 UTC, HuKuTa94 commented on architectureTests/src/main/kotlin/github/com/hukuta94/delivery/Rules.kt
> +}
Интересная идея! Попробую реализовать.

2024-08-05 07:43 UTC, HuKuTa94 commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/ApplicationPackageTest.kt
> +                .check(packageClasses)
Здесь имелось в виду, что в пакете application.query должны отсутствовать реализации. Наверное, можно боле выразительно составить тест, что в этом пакете нет классов, которые бы реализовали Query.

2024-08-05 07:45 UTC, HuKuTa94 commented on core/application/main/src/main/kotlin/github/com/hukuta94/delivery/core/application/query/common/LocationResponse.kt
>  package github.com.hukuta94.delivery.core.application.query.common
Оно итак везде ДТО по сути, просто здесь хранятся те ДТО, которые могут применяться в разных QueryResponse'aх - это такие root ДТО, которые агрегируют в себе данные используя другие ДТО в том числе и общие)

2024-08-05 07:46 UTC, HuKuTa94 commented on api/adapter/http/src/main/kotlin/github/com/hukuta94/delivery/api/adapter/http/courier/CourierControllerV1.kt
>  import java.util.*
импортировать всё и сразу?)

2024-08-05 19:38 UTC, HuKuTa94 commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/ApiPackageTest.kt
> +        }
Реализовал такой синтаксис тестов:

```kotlin
APPLICATION_EVENT_PACKAGE onlyDependsOn packages(
    APPLICATION_USECASE_PACKAGE,
    APPLICATION_PORT_PACKAGE,
    DOMAIN_LAYER_PACKAGE
)
```

2024-08-05 19:38 UTC, HuKuTa94 commented on architectureTests/src/test/kotlin/github/com/hukuta94/delivery/GeneralArchitectureTest.kt
> +
Решил выпилить эти тесты, т.к. с упрощением синтаксиса написания тестов, этот класс стал избыточен.

2024-08-05 19:40 UTC, HuKuTa94 commented on architectureTests/src/main/kotlin/github/com/hukuta94/delivery/Rules.kt
> +}
Реализовал такой синтаксис тестов:

```kotlin
APPLICATION_EVENT_PACKAGE onlyDependsOn packages(
    APPLICATION_USECASE_PACKAGE,
    APPLICATION_PORT_PACKAGE,
    DOMAIN_LAYER_PACKAGE
)

APPLICATION_PORT_PACKAGE onlyDependsOn DOMAIN_LAYER_PACKAGE

 APPLICATION_QUERY_PACKAGE onlyDependsOn self()
```

2024-08-12 07:57 UTC, merged